In [1]:
import sys

sys.path.append('/Users/ravi.tej/Desktop/ML/Recommendations/cambrian/')

from src.clustering.ClustersResetService import ClustersResetService
from src.clustering.ClusterAssignmentService import ClusterAssignmentService

import hydra
import os
from hydra import compose, initialize

/Users/ravi.tej/anaconda3/envs/recoenv/lib/python3.11/site-packages/umap/distances.py:1063: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
/Users/ravi.tej/anaconda3/envs/recoenv/lib/python3.11/site-packages/umap/distances.py:1071: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
/Users/ravi.tej/anaconda3/envs/recoenv/lib/python3.11/site-pac

In [6]:
parent_folder = '/Users/ravi.tej/Desktop/ML/Recommendations/cambrian/'
data_folder = parent_folder + 'data/'

with initialize(config_path="../../conf"):
    # Compose the configuration
    cfg = compose(config_name="ClustersResetService.yaml")

import os

import xml.etree.ElementTree as ET

tree = ET.parse('../../conf/application.run.xml')
root = tree.getroot()

envs_element = root.find('./configuration/envs')
for variable in envs_element.findall('env'):
    name = variable.get('name')
    value = variable.get('value')
    os.environ[name] = value

In [7]:
clustering = ClustersResetService(model_name='BAAI/bge-small-en',dataset_path=data_folder + 'formatted_articles_data_2023_embeddings_bge_small_en.parquet', 
                                 documents_column_name='title_summary', embeddings_column_name='embeddings',cfg = cfg, random_state= 86)

bertopic model instantiated


2023-09-26 08:30:36,293 - BERTopic - Reduced dimensionality
2023-09-26 08:32:42,571 - BERTopic - Clustered reduced embeddings
100%|██████████| 273/273 [00:02<00:00, 112.57it/s]


model fit to documents


Upload 3 LFS files:   0%|          | 0/3 [00:00<?, ?it/s]

ctfidf.safetensors:   0%|          | 0.00/25.1M [00:00<?, ?B/s]

ctfidf_config.json:   0%|          | 0.00/30.3M [00:00<?, ?B/s]

topic_embeddings.safetensors:   0%|          | 0.00/422k [00:00<?, ?B/s]

docs assigned to balanced clusters


In [8]:
clustering.run_id

'ZigzagRabbitPanda'

In [9]:
clustering.cluster_hierarchy_df

parent_id                                        parent_name  \
32         66                          india_bank_ipo_2023_crore   
31         65                             ipo_india_new_2023_tax   
30         64                          ipo_india_fund_market_new   
29         63                          bank_rates_rbi_rate_crore   
28         62                        ipo_fund_market_funds_india   
..        ...                                                ...   
62         29  gold_sovereign_sovereign gold_gold prices_aksh...   
63         30                   5g_india_apple_commerce_reliance   
64         31                         modi_yoga_pm_visit_pm modi   
65         32                 electric_ev_vehicles_honda_wheeler   
66         33                              gst_cbic_rs_tax_crore   

                                 child_storyline_list child_left_id  \
32  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...            63   
31  [0, 1, 2, 3, 6, 7, 8, 9, 10, 11, 12, 13, 15, 1...            64   
30  [0, 1, 2, 3, 6, 8, 9, 10, 11, 12, 13, 15, 18, ...            54   
29                         [4, 5, 14, 16, 17, 19, 21]            34   
28  [0, 1, 3, 6, 8, 9, 10, 11, 12, 15, 18, 22, 23,...            61   
..                                                ...           ...   
62                                               None          None   
63                                               None          None   
64                                               None          None   
65                                               None          None   
66                                               None          None   

                     child_left_name child_right_id  \
32         bank_rates_rbi_rate_crore             65   
31         ipo_india_fund_market_new             41   
30  pawar_bjp_congress_modi_minister             62   
29    profit_crore_net_net profit_q3             57   
28      ipo_fund_market_funds_mutual             40   
..                               ...            ...   
62                              None           None   
63                              None           None   
64                              None           None   
65                              None           None   
66                              None           None   

                    child_right_name  distance  level  num_docs  \
32            ipo_india_new_2023_tax  1.249900      0    3918.0   
31  tax_income_income tax_budget_itr  1.234434      1    3014.0   
30       ipo_fund_market_funds_india  1.137340      2    2752.0   
29         bank_rates_rbi_rate_fixed  1.098115      1     904.0   
28     ai_whatsapp_users_feature_app  1.079429      3    2165.0   
..                               ...       ...    ...       ...   
62                              None       NaN      9      51.0   
63                              None       NaN      8      50.0   
64                              None       NaN      6      47.0   
65                              None       NaN      9      44.0   
66                              None       NaN      7      40.0   

                                             doc_list  
32  [72, 261, 279, 1450, 1980, 2023, 2083, 2120, 2...  
31  [172, 252, 846, 1301, 1337, 3188, 3203, 3218, ...  
30  [172, 252, 846, 1301, 1337, 3188, 3203, 3218, ...  
29  [72, 261, 279, 1450, 1980, 2023, 2083, 2120, 2...  
28  [3, 7, 2206, 2210, 2212, 2214, 2219, 2225, 226...  
..                                                ...  
62  [21, 1036, 1388, 1451, 1518, 1590, 1598, 1617,...  
63  [57, 80, 86, 203, 301, 338, 1098, 1104, 1114, ...  
64  [70, 87, 243, 251, 344, 366, 432, 582, 608, 70...  
65  [54, 69, 144, 165, 239, 265, 363, 421, 474, 12...  
66  [82, 155, 218, 222, 299, 302, 413, 436, 452, 4...  

[67 rows x 11 columns]

In [63]:
[x.lower() for x in clustering.cluster_hierarchy_df.columns]

['parent_id',
 'parent_name',
 'topics',
 'child_left_id',
 'child_left_name',
 'child_right_id',
 'child_right_name',
 'distance',
 'num_docs',
 'doc_list']

In [68]:
clustering.cluster_hierarchy_df['Child_Right_ID'].apply(lambda x: int(x) if x is not None else x)

272    545.0
271    544.0
270    540.0
269    541.0
268    533.0
       ...  
542      NaN
543      NaN
544      NaN
545      NaN
546      NaN
Name: Child_Right_ID, Length: 547, dtype: float64

In [59]:
for index, row in clustering.cluster_hierarchy_df.iterrows():
    print(row['Parent_ID'])

546
545
544
543
542
541
540
539
538
537
536
535
534
533
532
531
530
529
528
527
526
525
524
523
522
521
520
519
518
517
516
515
514
513
512
511
510
509
508
507
506
505
504
503
502
501
500
499
498
497
496
495
494
493
492
491
490
489
488
487
486
485
484
483
482
481
480
479
478
477
476
475
474
473
472
471
470
469
468
467
466
465
464
463
462
461
460
459
458
457
456
455
454
453
452
451
450
449
448
447
446
445
444
443
442
441
440
439
438
437
436
435
434
433
432
431
430
429
428
427
426
425
424
423
422
421
420
419
418
417
416
415
414
413
412
411
410
409
408
407
406
405
404
403
402
401
400
399
398
397
396
395
394
393
392
391
390
389
388
387
386
385
384
383
382
381
380
379
378
377
376
375
374
373
372
371
370
369
368
367
366
365
364
363
362
361
360
359
358
357
356
355
354
353
352
351
350
349
348
347
346
345
344
343
342
341
340
339
338
337
336
335
334
333
332
331
330
329
328
327
326
325
324
323
322
321
320
319
318
317
316
315
314
313
312
311
310
309
308
307
306
305
304
303
302
301
300
299
298
297


In [5]:
len(clustering.balanced_clusters)

27

In [6]:
clustering.topic_cluster_map['2']

'399'

In [8]:
from copy import deepcopy

In [9]:
bt_model = deepcopy(clustering.bertopic_model)

In [10]:
bt_model.topic_cluster_map = clustering.topic_cluster_map

In [13]:
bt_model.save("bertopic_bge_small_24_sep_with_topic_cluster_map", serialization="safetensors", save_ctfidf=True, save_embedding_model='BAAI/bge-small-en')

In [15]:
from bertopic import BERTopic

In [16]:
bt_model_load = BERTopic.load("bertopic_bge_small_24_sep_with_topic_cluster_map/")

In [17]:
bt_model_load.topic_cluster_map

AttributeError: 'BERTopic' object has no attribute 'topic_cluster_map'

### Observation

- can't store topic cluster mapping with in the object as it will be lost. need to save it separately

### Saving topic cluster mapping

In [19]:
import json

with open('topic_cluster_map.json', 'w') as f:
    json.dump(clustering.topic_cluster_map, f)

In [20]:
with open('topic_cluster_map.json') as f:
    my_dict = json.load(f)

In [21]:
my_dict

{'28': '540',
 '36': '540',
 '56': '540',
 '84': '540',
 '89': '540',
 '119': '540',
 '133': '540',
 '145': '540',
 '178': '540',
 '206': '540',
 '208': '540',
 '214': '540',
 '217': '540',
 '229': '540',
 '231': '540',
 '233': '540',
 '253': '540',
 '270': '540',
 '271': '540',
 '5': '537',
 '10': '537',
 '26': '537',
 '53': '537',
 '58': '537',
 '73': '537',
 '86': '537',
 '108': '537',
 '111': '537',
 '121': '537',
 '123': '537',
 '142': '537',
 '155': '537',
 '159': '537',
 '161': '537',
 '168': '537',
 '173': '537',
 '176': '537',
 '181': '537',
 '199': '537',
 '205': '537',
 '209': '537',
 '212': '537',
 '222': '537',
 '246': '537',
 '268': '537',
 '6': '531',
 '29': '531',
 '40': '531',
 '47': '531',
 '62': '531',
 '66': '531',
 '70': '531',
 '72': '531',
 '74': '531',
 '102': '531',
 '107': '531',
 '116': '531',
 '118': '531',
 '140': '531',
 '144': '531',
 '147': '531',
 '151': '531',
 '198': '531',
 '203': '531',
 '219': '531',
 '227': '531',
 '239': '531',
 '262': '531',
 '2

In [ ]:
import os

In [ ]:
os.listdir('bertopic_bge_small_24_sep/')

['ctfidf.bin',
 'config.json',
 'ctfidf_config.json',
 'topic_embeddings.bin',
 'topic_embeddings.safetensors',
 'ctfidf.safetensors',
 'topics.json']

### Checking impact of document values on topic assignment when embeddings are present

In [47]:
sent = 'air india stock'

In [46]:
bt_model.transform(sent)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2023-09-24 22:48:34,728 - BERTopic - Reduced dimensionality
2023-09-24 22:48:34,761 - BERTopic - Calculated probabilities with HDBSCAN
2023-09-24 22:48:34,762 - BERTopic - Predicted clusters


([4],
 array([[0.0026719 , 0.00206812, 0.00250062, 0.00158924, 0.37660883,
         0.00193075, 0.00211946, 0.00238874, 0.00248979, 0.00207601,
         0.00229767, 0.00238942, 0.00243978, 0.00201353, 0.00241267,
         0.00249926, 0.00291895, 0.00167241, 0.00242037, 0.00183013,
         0.00095102, 0.00224833, 0.00255905, 0.00208214, 0.00237846,
         0.00261381, 0.00252505, 0.00321648, 0.00236978, 0.00208796,
         0.0031313 , 0.00200513, 0.00211382, 0.00145327, 0.00214443,
         0.00219239, 0.00273182, 0.0011454 , 0.00169579, 0.00270988,
         0.00215127, 0.00288471, 0.00165907, 0.00245389, 0.00337377,
         0.0022108 , 0.00202883, 0.00212772, 0.00234039, 0.00225086,
         0.00369306, 0.00175732, 0.00230648, 0.00312236, 0.00262118,
         0.00308586, 0.0025032 , 0.00282081, 0.00250094, 0.00239544,
         0.00209556, 0.00283579, 0.00209964, 0.00297873, 0.00396337,
         0.00271907, 0.00228285, 0.00147142, 0.00236018, 0.00285774,
         0.00221446, 0.00275

In [49]:
emb = bt_model.embedding_model.embed_documents(sent)

In [50]:
bt_model.transform(documents=[sent],embeddings=emb.reshape(-1,1).T)

2023-09-24 22:49:15,397 - BERTopic - Reduced dimensionality
2023-09-24 22:49:15,431 - BERTopic - Calculated probabilities with HDBSCAN
2023-09-24 22:49:15,431 - BERTopic - Predicted clusters


([4],
 array([[0.0026719 , 0.00206812, 0.00250062, 0.00158924, 0.37660883,
         0.00193075, 0.00211946, 0.00238874, 0.00248979, 0.00207601,
         0.00229767, 0.00238942, 0.00243978, 0.00201353, 0.00241267,
         0.00249926, 0.00291895, 0.00167241, 0.00242037, 0.00183013,
         0.00095102, 0.00224833, 0.00255905, 0.00208214, 0.00237846,
         0.00261381, 0.00252505, 0.00321648, 0.00236978, 0.00208796,
         0.0031313 , 0.00200513, 0.00211382, 0.00145327, 0.00214443,
         0.00219239, 0.00273182, 0.0011454 , 0.00169579, 0.00270988,
         0.00215127, 0.00288471, 0.00165907, 0.00245389, 0.00337377,
         0.0022108 , 0.00202883, 0.00212772, 0.00234039, 0.00225086,
         0.00369306, 0.00175732, 0.00230648, 0.00312236, 0.00262118,
         0.00308586, 0.0025032 , 0.00282081, 0.00250094, 0.00239544,
         0.00209556, 0.00283579, 0.00209964, 0.00297873, 0.00396337,
         0.00271907, 0.00228285, 0.00147142, 0.00236018, 0.00285774,
         0.00221446, 0.00275

In [51]:
bt_model.transform(documents=['something else completeleeysdlkfjsd'],embeddings=emb.reshape(-1,1).T)

2023-09-24 22:49:30,445 - BERTopic - Reduced dimensionality
2023-09-24 22:49:30,478 - BERTopic - Calculated probabilities with HDBSCAN
2023-09-24 22:49:30,478 - BERTopic - Predicted clusters


([4],
 array([[0.0026719 , 0.00206812, 0.00250062, 0.00158924, 0.37660883,
         0.00193075, 0.00211946, 0.00238874, 0.00248979, 0.00207601,
         0.00229767, 0.00238942, 0.00243978, 0.00201353, 0.00241267,
         0.00249926, 0.00291895, 0.00167241, 0.00242037, 0.00183013,
         0.00095102, 0.00224833, 0.00255905, 0.00208214, 0.00237846,
         0.00261381, 0.00252505, 0.00321648, 0.00236978, 0.00208796,
         0.0031313 , 0.00200513, 0.00211382, 0.00145327, 0.00214443,
         0.00219239, 0.00273182, 0.0011454 , 0.00169579, 0.00270988,
         0.00215127, 0.00288471, 0.00165907, 0.00245389, 0.00337377,
         0.0022108 , 0.00202883, 0.00212772, 0.00234039, 0.00225086,
         0.00369306, 0.00175732, 0.00230648, 0.00312236, 0.00262118,
         0.00308586, 0.0025032 , 0.00282081, 0.00250094, 0.00239544,
         0.00209556, 0.00283579, 0.00209964, 0.00297873, 0.00396337,
         0.00271907, 0.00228285, 0.00147142, 0.00236018, 0.00285774,
         0.00221446, 0.00275

In [69]:
clustering.documents

['Article removed on legal advice This article has been removed on legal advice',
 'More than 2.30 lakh consumers registered for Guj govt’s solar rooftop scheme in two years\xa0 Ahmedabad topped with 34,794 household consumer registrations, followed by Vadodara with 33,918, Surat 30,918 and Rajkot 24,118 consumers, the minister said.',
 'Explainer: Interlocking in Railway Operations Railways minister Ashwini Vaishnaw said that a change in the electronic interlocking and the setting of the point machine caused the accident involving the Shalimar Chennai Central Coromandel Express, in which 275 people died. ',
 "Maharashtra SSC Result 2023 Highlights: MSBSHSE Class 10 results OUT, 93.83% students bag success Maharashtra Class 10th SSC Result 2023 Highlights: To view their SSC results, students need to provide their board exam seat number and their mother's first name, as stated on their admit cards or application forms.",
 'Who is Piyush Gupta, the CEO of DBS Group who earns Rs 25 lakh p

In [55]:
clustering.cluster_hierarchy_df

Parent_ID                                        Parent_Name  \
272       546                       stock_today_2023_price_india   
271       545                            india_2023_new_adani_rs   
270       544                            india_2023_new_rs_adani   
269       543                            india_2023_adani_new_rs   
268       542                            2023_new_india_tax_said   
..        ...                                                ...   
542       269  business ideas_ideas_business_ideas low_low in...   
543       270              skoda_virtus_volkswagen_taigun_slavia   
544       271            renault_nissan_expo_auto expo_expo 2023   
545       272  unemployment_unemployment rate_claims_jobless_...   
546       273  powergrid_powergrid stock_powergrid closed_mon...   

                                                Topics Child_Left_ID  \
272  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...           515   
271  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...           519   
270  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...           543   
269  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...           542   
268  [0, 1, 2, 3, 4, 6, 7, 8, 9, 11, 12, 13, 14, 15...           539   
..                                                 ...           ...   
542                                               None          None   
543                                               None          None   
544                                               None          None   
545                                               None          None   
546                                               None          None   

                              Child_Left_Name Child_Right_ID  \
272      stock_stock price_closed_price_share            545   
271  nifty_sensex_share market_pts_bank nifty            544   
270                   india_2023_adani_new_rs            540   
269                   2023_new_india_tax_said            541   
268                 2023_tax_new_india_credit            533   
..                                        ...            ...   
542                                      None           None   
543                                      None           None   
544                                      None           None   
545                                      None           None   
546                                      None           None   

                            Child_Right_Name  Distance  num_docs  \
272                  india_2023_new_adani_rs  3.244247     41976   
271                  india_2023_new_rs_adani  1.926983     39783   
270  maruti_suzuki_maruti suzuki_electric_ev  1.835385     38850   
269          adani_gold_stocks_rate_dividend  1.702763     37119   
268         pakistan_modi_air_delhi_minister  1.627899     30246   
..                                       ...       ...       ...   
542                                     None       NaN        40   
543                                     None       NaN        40   
544                                     None       NaN        40   
545                                     None       NaN        40   
546                                     None       NaN        40   

                                              doc_list  
272  [205, 287, 343, 350, 400, 473, 707, 763, 765, ...  
271  [207, 5418, 6332, 13278, 13536, 14408, 15758, ...  
270  [5071, 6248, 12347, 31425, 31431, 31437, 31438...  
269  [5071, 6248, 12347, 31425, 31431, 31437, 31438...  
268  [5071, 6248, 12347, 31425, 31431, 31437, 31438...  
..                                                 ...  
542  [31198, 31446, 31448, 31454, 31458, 31470, 314...  
543  [6589, 14295, 14417, 14422, 14446, 14467, 1453...  
544  [421, 3726, 10252, 11074, 11667, 11688, 12445,...  
545  [638, 1067, 1084, 15541, 16049, 16417, 16522, ...  
546  [19680, 19833, 19951, 20189, 20271, 20346, 204...  

[547 rows x 10 columns]

In [56]:
clustering.topic_cluster_map

{'28': '540',
 '36': '540',
 '56': '540',
 '84': '540',
 '89': '540',
 '119': '540',
 '133': '540',
 '145': '540',
 '178': '540',
 '206': '540',
 '208': '540',
 '214': '540',
 '217': '540',
 '229': '540',
 '231': '540',
 '233': '540',
 '253': '540',
 '270': '540',
 '271': '540',
 '5': '537',
 '10': '537',
 '26': '537',
 '53': '537',
 '58': '537',
 '73': '537',
 '86': '537',
 '108': '537',
 '111': '537',
 '121': '537',
 '123': '537',
 '142': '537',
 '155': '537',
 '159': '537',
 '161': '537',
 '168': '537',
 '173': '537',
 '176': '537',
 '181': '537',
 '199': '537',
 '205': '537',
 '209': '537',
 '212': '537',
 '222': '537',
 '246': '537',
 '268': '537',
 '6': '531',
 '29': '531',
 '40': '531',
 '47': '531',
 '62': '531',
 '66': '531',
 '70': '531',
 '72': '531',
 '74': '531',
 '102': '531',
 '107': '531',
 '116': '531',
 '118': '531',
 '140': '531',
 '144': '531',
 '147': '531',
 '151': '531',
 '198': '531',
 '203': '531',
 '219': '531',
 '227': '531',
 '239': '531',
 '262': '531',
 '2

In [ ]:
clustering.bertopic_model.

In [53]:
clustering.bertopic_model.transform(documents=[sent])

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2023-09-24 23:10:55,881 - BERTopic - Reduced dimensionality
2023-09-24 23:10:55,919 - BERTopic - Calculated probabilities with HDBSCAN
2023-09-24 23:10:55,919 - BERTopic - Predicted clusters


([4],
 array([[0.0026719 , 0.00206812, 0.00250062, 0.00158924, 0.37660883,
         0.00193075, 0.00211946, 0.00238874, 0.00248979, 0.00207601,
         0.00229767, 0.00238942, 0.00243978, 0.00201353, 0.00241267,
         0.00249926, 0.00291895, 0.00167241, 0.00242037, 0.00183013,
         0.00095102, 0.00224833, 0.00255905, 0.00208214, 0.00237846,
         0.00261381, 0.00252505, 0.00321648, 0.00236978, 0.00208796,
         0.0031313 , 0.00200513, 0.00211382, 0.00145327, 0.00214443,
         0.00219239, 0.00273182, 0.0011454 , 0.00169579, 0.00270988,
         0.00215127, 0.00288471, 0.00165907, 0.00245389, 0.00337377,
         0.0022108 , 0.00202883, 0.00212772, 0.00234039, 0.00225086,
         0.00369306, 0.00175732, 0.00230648, 0.00312236, 0.00262118,
         0.00308586, 0.0025032 , 0.00282081, 0.00250094, 0.00239544,
         0.00209556, 0.00283579, 0.00209964, 0.00297873, 0.00396337,
         0.00271907, 0.00228285, 0.00147142, 0.00236018, 0.00285774,
         0.00221446, 0.00275

In [54]:
clustering.topic_cluster_map['4']

'512'

In [52]:
bt_model.transform(documents=['something else completeleeysdlkfjsd'])

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2023-09-24 22:49:44,999 - BERTopic - Reduced dimensionality
2023-09-24 22:49:45,033 - BERTopic - Calculated probabilities with HDBSCAN
2023-09-24 22:49:45,034 - BERTopic - Predicted clusters


([-1],
 array([[3.55802196e-85, 3.07191844e-88, 2.66281912e-88, 3.05179162e-90,
         1.99677817e-87, 3.76163534e-90, 2.48682988e-87, 2.14176477e-87,
         2.24500074e-86, 3.42009455e-88, 2.06707480e-87, 3.13866562e-87,
         4.49701597e-79, 2.63450717e-79, 2.33933514e-88, 1.11998571e-88,
         2.04749227e-87, 1.90491581e-90, 4.40086283e-79, 7.23425720e-90,
         1.94460888e-91, 3.34764869e-88, 3.13561898e-01, 3.02787643e-79,
         2.34537650e-88, 2.43846673e-87, 2.23206572e-87, 2.11750392e-87,
         1.91522905e-87, 2.48568291e-87, 2.40883458e-87, 2.02409168e-90,
         2.21271007e-87, 2.36855646e-90, 3.05194177e-79, 2.24413736e-87,
         2.20555497e-87, 1.81190296e-91, 3.22531242e-89, 2.60052823e-87,
         2.40744939e-87, 2.28143671e-87, 6.87134253e-89, 2.02828531e-87,
         1.90293132e-87, 2.25224210e-87, 2.15372904e-87, 2.44616433e-87,
         6.36580663e-88, 4.66117926e-88, 2.14506741e-87, 7.11917534e-89,
         2.49064635e-87, 2.08878222e-87, 3.6

In [28]:
emb

array([-3.44888687e-01,  1.14216134e-01,  8.80852193e-02,  9.05926377e-02,
        2.68557966e-01, -1.06633082e-01,  2.57639796e-01, -1.98818535e-01,
       -2.02766269e-01,  1.58549100e-03,  2.18597986e-02, -1.15172751e-01,
        6.11584783e-01,  1.75956190e-02,  1.52939409e-01,  1.27758056e-01,
       -1.09963834e-01,  1.23115242e-01, -2.86685467e-01,  1.74872756e-01,
        2.50179917e-01, -4.43214297e-01,  2.30505615e-01, -3.55359316e-01,
       -6.20545149e-01,  1.83835641e-01,  1.93594992e-01, -9.73174199e-02,
       -3.99963081e-01, -1.59517980e+00, -1.21508501e-01, -4.58478451e-01,
       -2.07844079e-01,  2.33702064e-02,  3.50457639e-01,  1.05179563e-01,
       -3.10244083e-01,  2.36035585e-01, -2.60600597e-01,  3.14955682e-01,
        3.83389443e-01,  2.60670245e-01, -5.14367104e-01, -2.66884625e-01,
       -2.11097583e-01, -4.91341025e-01, -6.46622926e-02, -1.22755557e-01,
        6.49000168e-01, -6.31727099e-01, -3.68839979e-01, -2.12463751e-01,
        1.42413393e-01,  

In [21]:
clustering.bertopic_model.topic_labels_[259]

'259_ntpc_ntpc stock_ntpc closed_182'

In [22]:
from sklearn.metrics.pairwise import cosine_similarity

In [23]:
a1 = clustering.bertopic_model.topic_embeddings_[260]
a2 = clustering.bertopic_model.topic_embeddings_[244]

In [26]:
cosine_similarity(a1.reshape(1,-1), a2.reshape(1,-1))

array([[0.89435575]])

In [7]:
clustering.cluster_hierarchy_df[clustering.cluster_hierarchy_df.Parent_ID.isin(clustering.balanced_clusters)]['num_docs'].describe([0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])

count      27.000000
mean     1554.666667
std      1265.603201
min       118.000000
10%       214.200000
20%       288.400000
30%       559.800000
40%       820.200000
50%       979.000000
60%      1815.000000
70%      2305.800000
80%      2933.800000
90%      3236.800000
max      3931.000000
Name: num_docs, dtype: float64

In [8]:
clustering.cluster_hierarchy_df[clustering.cluster_hierarchy_df.Parent_ID.isin(clustering.balanced_clusters)]

Parent_ID                                        Parent_Name  \
266       540            maruti_suzuki_maruti suzuki_electric_ev   
263       537            adani_stocks_dividend_adani group_crore   
257       531                 insurance_credit_mutual_best_funds   
256       530                         gold_rate_crude_dollar_oil   
254       528              vande_train_vande bharat_rainfall_imd   
252       526                      bjp_modi_trump_pawar_congress   
245       519           nifty_sensex_share market_pts_bank nifty   
241       515               stock_stock price_closed_price_share   
238       512               air_pakistan_ukraine_russia_aircraft   
237       511                   campaign_brand_film_codes_redeem   
229       503                  tax_gst_income_income tax_section   
219       493                         ipl_ipl 2023_match_vs_runs   
214       488                  apple_5g_twitter_oneplus_whatsapp   
198       472         hydrogen_green_solar_green hydrogen_energy   
150       424         population_women_gender_statistical_parity   
147       421          pension_epfo_nps_higher pension_provident   
140       414  msmes_msme_finance msmes_credit finance_busine...   
139       413          paytm_zomato_swiggy_paytm shares_delivery   
138       412      crypto_sebi_bitcoin_reportedly_cryptocurrency   
134       408            byju_layoffs_employees_funding_startups   
125       399             covid_students_education_health_result   
118       392               ai_chatgpt_openai_chatbot_generative   
105       379                insolvency_nclt_zee_rcap_resolution   
38        312     student_student loan_loan_programs_forgiveness   
23        297              ipo_gmp_issue_subscribed_subscription   
19        293                   visa_visas_immigration_1b_canada   
15        289        real estate_estate_real_housing_residential   

                                                Topics Child_Left_ID  \
266  [28, 36, 56, 84, 89, 119, 133, 145, 178, 206, ...           502   
263  [5, 10, 26, 53, 58, 73, 86, 108, 111, 121, 123...           330   
257  [6, 29, 40, 47, 62, 66, 70, 72, 74, 102, 107, ...           529   
256  [20, 25, 32, 33, 45, 61, 67, 68, 80, 81, 91, 1...           480   
254             [27, 41, 44, 50, 63, 75, 97, 138, 232]           470   
252  [30, 43, 46, 57, 69, 71, 76, 79, 90, 94, 100, ...           517   
245          [42, 51, 96, 99, 129, 177, 188, 225, 240]           390   
241  [52, 93, 113, 125, 135, 146, 153, 157, 165, 17...           317   
238  [4, 16, 31, 55, 64, 65, 87, 88, 131, 183, 190,...           499   
237  [12, 14, 18, 22, 37, 48, 60, 77, 95, 98, 101, ...           510   
229            [7, 35, 39, 59, 85, 112, 166, 186, 223]           498   
219                  [23, 34, 122, 126, 185, 197, 202]           345   
214                           [3, 11, 13, 38, 54, 127]           420   
198                           [78, 179, 189, 216, 220]           409   
150                                         [160, 255]           255   
147                                    [103, 106, 257]           340   
140                                           [8, 234]             8   
139                                         [154, 174]           154   
138                                            [1, 19]            19   
134                                      [21, 24, 158]           393   
125                                             [0, 2]             0   
118                                       [9, 49, 175]           175   
105                                    [137, 156, 242]           343   
38                                      [82, 130, 224]           279   
23                                            [17, 83]            17   
19                                           [92, 124]           124   
15                                           [15, 244]           244   

                                       Child_Left_Name Child_Right_ID  \
266      

In [17]:
clustering.cluster_hierarchy_df[clustering.cluster_hierarchy_df.Parent_ID.isin(clustering.balanced_clusters)].sort_values('Topics',ascending = False).tail(10)

Parent_ID                                        Parent_Name Topics  \
500       227                   inflows_funds_equity_amfi_mutual   None   
507       234  subsidy_fertiliser_kisan_pm kisan_fertiliser s...   None   
516       243         dr reddy_reddy_dr_reddy stock_reddy closed   None   
517       244   real estate_estate_real_crowdfunding_invest real   None   
520       247  hindustan_hindustan unilever_unilever_unilver_...   None   
532       259                ntpc_ntpc stock_ntpc closed_182_185   None   
536       263           debt_debt mutual_funds_mutual_debt funds   None   
537       264          plane_nepal_crash_plane crash_nepal plane   None   
539       266           ultra cem_cem_ultra_cem stock_cem closed   None   
541       268  jhunjhunwala_rekha jhunjhunwala_rekha_jhunjhun...   None   

    Child_Left_ID Child_Left_Name Child_Right_ID Child_Right_Name  Distance  \
500          None            None           None             None       NaN   
507          None            None           None             None       NaN   
516          None            None           None             None       NaN   
517          None            None           None             None       NaN   
520          None            None           None             None       NaN   
532          None            None           None             None       NaN   
536          None            None           None             None       NaN   
537          None            None           None             None       NaN   
539          None            None           None             None       NaN   
541          None            None           None             None       NaN   

     num_docs                                           doc_list  
500        48  [1427, 1478, 1530, 1538, 1547, 1574, 1654, 168...  
507        46  [426, 731, 904, 1267, 1557, 1594, 1820, 1901, ...  
516        45  [13500, 13639, 18999, 19285, 19453, 19733, 197...  
517        45  [31825, 31973, 32016, 32024, 32363, 32484, 326...  
520        44  [9374, 19066, 19288, 19591, 20182, 20389, 2044...  
532        42  [19234, 20132, 20475, 20483, 20511, 20753, 208...  
536        41  [1831, 1848, 3948, 4417, 4614, 4925, 4955, 497...  
537        41  [4273, 21765, 23672, 26908, 26977, 27064, 2743...  
539        41  [12657, 19446, 19566, 19714, 19757, 19906, 200...  
541        40  [9583, 10402, 21922, 24265, 24828, 24835, 2492...

In [8]:
docs = clustering.dataset['title_summary']

In [9]:
hierarchy_df = clustering.bertopic_model.hierarchical_topics(docs)

100%|██████████| 273/273 [00:02<00:00, 115.15it/s]


In [34]:
set(clustering.bertopic_model.topics_)

{-1,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 

In [ ]:
hierarchy_df[~hierarchy_df.Parent_ID.isin(left_topics)]

Parent_ID                   Parent_Name  \
272       546  stock_today_2023_price_india   

                                                Topics Child_Left_ID  \
272  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...           515   

                          Child_Left_Name Child_Right_ID  \
272  stock_stock price_closed_price_share            545   

            Child_Right_Name  Distance  
272  india_2023_new_adani_rs  3.244247

In [ ]:
hierarchy_df[hierarchy_df.Parent_ID == 2]

Empty DataFrame
Columns: [Parent_ID, Parent_Name, Topics, Child_Left_ID, Child_Left_Name, Child_Right_ID, Child_Right_Name, Distance]
Index: []

In [ ]:
len(left_topics)

546

In [11]:
hierarchy_df[hierarchy_df.Child_Left_ID.isnull()]

Empty DataFrame
Columns: [Parent_ID, Parent_Name, Topics, Child_Left_ID, Child_Left_Name, Child_Right_ID, Child_Right_Name, Distance]
Index: []

In [6]:
clustering.cluster_hierarchy_df_old

Parent_ID                                        Parent_Name  \
272       546                       stock_today_2023_price_india   
271       545                            india_2023_new_adani_rs   
270       544                            india_2023_new_rs_adani   
269       543                            india_2023_adani_new_rs   
268       542                            2023_new_india_tax_said   
..        ...                                                ...   
4         278  insurance_life insurance_life_health insurance...   
3         277  day trading_trading guide_guide today_guide_bu...   
2         276  monitor stock_stock_stock price_closed_updates...   
1         275   gold_gold price_gold prices_gold rate_rate today   
0         274           sensex_pts_share market_nifty_highlights   

                                                Topics Child_Left_ID  \
272  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...           515   
271  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...           519   
270  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...           543   
269  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...           542   
268  [0, 1, 2, 3, 4, 6, 7, 8, 9, 11, 12, 13, 14, 15...           539   
..                                                 ...           ...   
4                                             [40, 70]            40   
3                                           [159, 181]           159   
2                                           [192, 252]           192   
1                                            [20, 120]            20   
0                                           [177, 225]           177   

                                       Child_Left_Name Child_Right_ID  \
272               stock_stock price_closed_price_share            545   
271           nifty_sensex_share market_pts_bank nifty            544   
270                            india_2023_adani_new_rs            540   
269                            2023_new_india_tax_said            541   
268                          2023_tax_new_india_credit            533   
..                                                 ...            ...   
4    insurance_life insurance_health insurance_life...             70   
3    day trading_stocks_buy sell_buy_experts recomm...            181   
2    monitor stock_stock_stock price_share_updates ...            252   
1                 gold_gold prices_silver_ounce_prices            120   
0             sensex_share market_nifty_pts_highlights            225   

                                      Child_Right_Name  Distance  
272                            india_2023_new_adani_rs  3.244247  
271                            india_2023_new_rs_adani  1.926983  
270            maruti_suzuki_maruti suzuki_electric_ev  1.835385  
269                    adani_gold_stocks_rate_dividend  1.702763  
268                   pakistan_modi_air_delhi_minister  1.627899  
..                                                 ...       ...  
4         insurance_insurers_irdai_life_life insurance  0.493731  
3    trading guide_day trading_guide_guide today_ex...  0.437729  
2         monitor stock_stock_closed_stock price_price  0.397736  
1     gold_gold price_today gold_price india_gold rate  0.377114  
0             sensex_pts_share market_nifty_highlights  0.169132  

[273 rows x 8 columns]

In [7]:
clustering.cluster_hierarchy_df_old[clustering.cluster_hierarchy_df_old.Child_Right_ID.isnull()]

Empty DataFrame
Columns: [Parent_ID, Parent_Name, Topics, Child_Left_ID, Child_Left_Name, Child_Right_ID, Child_Right_Name, Distance]
Index: []

In [19]:
clustering.cluster_hierarchy_df[clustering.cluster_hierarchy_df.Child_Right_ID == '2']

Parent_ID                             Parent_Name  Topics Child_Left_ID  \
125       399  covid_students_education_health_result  [0, 2]             0   

                          Child_Left_Name Child_Right_ID  \
125  covid_health_covid 19_cancer_disease              2   

                                     Child_Right_Name  Distance  level  \
125  students_education_result_university_result 2023  0.892333     22   

     num_docs                                           doc_list  
125      3084  [35, 41, 104, 115, 197, 199, 308, 323, 346, 41...

In [23]:
s = set(clustering.bertopic_model.topics_)

In [51]:
clustering.bertopic_model.hierarchical_topics

<bound method BERTopic.hierarchical_topics of <bertopic._bertopic.BERTopic object at 0x16434f410>>

In [28]:
df = clustering.cluster_hierarchy_df

In [36]:
topic = '0'

In [39]:
df[df.Parent_ID.isin(clustering.balanced_clusters)]

Parent_ID                                        Parent_Name  \
222       496           steel_motors_tata_tata steel_tata motors   
201       475                       notes_rbi_loan_banks_rs 2000   
198       472         hydrogen_green_solar_green hydrogen_energy   
197       471                      hotels_yatra_hotel_day_whisky   
194       468         court_supreme court_supreme_google_sisodia   
..        ...                                                ...   
11        285  coal_coal india_india stock_mines_coal production   
7         281        sbi_sbi life_sbi stock_monitor sbi_news sbi   
6         280                crore_profit_net_net profit_quarter   
4         278  insurance_life insurance_life_health insurance...   
1         275   gold_gold price_gold prices_gold rate_rate today   

                        Topics Child_Left_ID  \
222   [86, 123, 173, 199, 209]           368   
201   [66, 102, 147, 203, 262]           436   
198   [78, 179, 189, 216, 220]           409   
197  [149, 152, 167, 210, 248]           452   
194   [90, 100, 117, 180, 213]           453   
..                         ...           ...   
11                   [53, 168]            53   
7                   [200, 256]           200   
6                     [26, 73]            73   
4                     [40, 70]            40   
1                    [20, 120]            20   

                                       Child_Left_Name Child_Right_ID  \
222       motors_tata motors_eicher motors_eicher_tata            291   
201             loan_home_personal loan_loans_mortgage            381   
198            ncds_bonds_green bonds_green_debentures            438   
197          hotels_hotel_whisky_whiskies_destinations            440   
194         sisodia_manish sisodia_manish_kejriwal_aap            391   
..                                                 ...            ...   
11    coal_mines_coal india_coal production_production            168   
7       sbi_sbi stock_sbi closed_sbi share_monitor sbi            256   
6                    profit_bank_crore_net_bank baroda             26   
4    insurance_life insurance_health insurance_life...             70   
1                 gold_gold prices_silver_ounce_prices            120   

                                      Child_Right_Name  Distance  level  \
222     steel_tata steel_tata_steel closed_steel stock  1.110280      8   
201                       notes_rbi_rs 2000_2000_banks  1.020552     14   
198         hydrogen_green hydrogen_solar_energy_green  1.015158     16   
197                          yatra_day_doodle_eid_rath  1.014613     16   
194             google_court_supreme court_supreme_cci  1.007619     10   
..                                                 ...       ...    ...   
11   coal india_coal_india stock_india closed_monit...  0.595373      8   
7             sbi life_sbi_life_life stock_life closed  0.538983      6   
6                  crore_profit_net profit_revenue_net  0.533411      9   
4         insurance_insurers_irdai_life_life insurance  0.493731     11   
1     gold_gold price_today gold_price india_gold rate  0.377114      7   

     num_docs                                           doc_list  
222       402  [2528, 3223, 3391, 3517, 7480, 8287, 8416, 864...  
201       438  [4862, 6768, 14699, 15477, 31663, 32425, 32515...  
198       358  [1472, 1742, 1827, 1835, 2736, 4832, 5214, 521...  
197       324  [338, 3270, 3345, 3566, 4055, 4236, 8001, 8769...  
194       455  [349, 901, 1508, 1561, 1736, 4200, 4305, 4307,...  
..        ...                                                ...  
11        231  [99, 597, 645, 680, 690, 702, 755, 943, 987, 1...  
7          97  [606, 2034, 5256, 14854, 14946, 19745, 19857, ...  
6         462  [166, 260, 315, 354, 358, 378, 395, 467, 520, ...  
4         363  [1405, 1410, 1523, 1599, 1616, 1741, 1760, 177...  
1         484  [21, 1388, 1451, 1518, 1590, 1598, 1617, 1620,...  

[74 rows x 11 columns]

In [1]:
import dill
from sentence_transformers import SentenceTransformer
from bertopic import BERTopic

/Users/ravi.tej/anaconda3/envs/recoenv/lib/python3.11/site-packages/umap/distances.py:1063: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
/Users/ravi.tej/anaconda3/envs/recoenv/lib/python3.11/site-packages/umap/distances.py:1071: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
/Users/ravi.tej/anaconda3/envs/recoenv/lib/python3.11/site-pac

In [3]:
with open("ect_bge_small_search.dill", "rb") as f:
    ect = dill.load(f)

In [6]:
ect.bertopic_model.save?

Signature:
ect.bertopic_model.save(
    path,
    serialization: Literal['safetensors', 'pickle', 'pytorch'] = 'pickle',
    save_embedding_model: Union[bool, str] = True,
    save_ctfidf: bool = False,
)
Docstring:
Saves the model to the specified path or folder

When saving the model, make sure to also keep track of the versions
of dependencies and Python used. Loading and saving the model should
be done using the same dependencies and Python. Moreover, models
saved in one version of BERTopic should not be loaded in other versions.

Arguments:
    path: If `serialization` is 'safetensors' or `pytorch`, this is a directory.
          If `serialization` is `pickle`, then this is file.
    serialization: If `pickle`, the entire model will be pickled. If `safetensors`
                   or `pytorch` the model will be saved without the embedding,
                   dimensionality reduction, and clustering algorithms.
                   This is a very efficient format and typically advised

In [7]:
ect.bertopic_model.save("bertopic_bge_small_24_sep", serialization="safetensors", save_ctfidf=True, save_embedding_model='BAAI/bge-small-en')

In [8]:
model2 = BERTopic.load("bertopic_bge_small_24_sep/")

In [19]:
embeddings = ect.embeddings_model.encode('something value of something')

In [23]:
import numpy as np

In [33]:
embeddings.reshape(-1,1).T.shape

(1, 384)

In [40]:
t, p = ect.bertopic_model.transform(['the irrelevence of something that is not constant is baffeling'])

In [44]:
np.sum(p[0])

0.8209494511842498

In [54]:
model2.probabilities_

In [46]:
t1, p1 = model2.transform(['the irrelevence of something that is not constant is baffeling'])

In [52]:
p

array([[3.91221138e-05, 2.55740776e-05, 2.98452587e-05, 4.39697743e-05,
        2.64687432e-05, 2.08360983e-05, 1.63686283e-05, 1.71999532e-05,
        5.55572804e-04, 3.88023182e-05, 1.71205495e-05, 3.11932483e-05,
        1.78475300e-05, 8.40419465e-05, 3.27489352e-05, 2.81599818e-05,
        3.72404617e-05, 1.60449564e-05, 1.91512713e-05, 3.53547623e-05,
        2.80283938e-05, 9.22932053e-06, 4.14476368e-05, 2.10923527e-05,
        1.70274336e-05, 2.89476876e-05, 3.24499584e-05, 6.97930060e-05,
        1.68554753e-05, 4.52702336e-04, 1.86262706e-05, 2.76658696e-05,
        3.34740638e-05, 3.53950994e-05, 1.35592394e-05, 1.31459442e-05,
        6.65826584e-04, 6.09196969e-05, 2.44333141e-05, 2.07220862e-05,
        3.33650123e-05, 4.64038927e-05, 3.40202822e-05, 2.34386701e-05,
        3.38996522e-05, 2.60102693e-05, 4.79995829e-05, 2.08222642e-05,
        5.94676368e-05, 2.83845115e-05, 1.82645497e-05, 3.77159015e-05,
        1.66064370e-05, 1.56884207e-05, 1.93436018e-05, 1.947279

In [51]:
p1/(np.sum(p1)*5/4)

array([[0.00089995, 0.0008448 , 0.00087583, 0.00084053, 0.00088614,
        0.00084518, 0.00088604, 0.00081153, 0.00085954, 0.00088834,
        0.00087761, 0.00085886, 0.00085161, 0.00084868, 0.00085362,
        0.00083666, 0.00085579, 0.00086912, 0.00083049, 0.00085985,
        0.00084925, 0.00087237, 0.00086582, 0.00085155, 0.00083051,
        0.00084235, 0.00088569, 0.00086929, 0.00085543, 0.00083173,
        0.00086681, 0.00085628, 0.0008442 , 0.00082658, 0.00084014,
        0.00083488, 0.00085179, 0.0008625 , 0.00084998, 0.00085474,
        0.00085366, 0.00084982, 0.00082957, 0.00083012, 0.00083632,
        0.00084438, 0.00085935, 0.00085765, 0.00085487, 0.00084861,
        0.0008958 , 0.00083675, 0.00087528, 0.00084755, 0.00083118,
        0.0008551 , 0.0008356 , 0.00083613, 0.00084873, 0.00086398,
        0.00085732, 0.00081943, 0.00086487, 0.00086379, 0.00083319,
        0.00086032, 0.00085374, 0.00085081, 0.00085515, 0.0008391 ,
        0.00085094, 0.00086016, 0.00086287, 0.00

In [35]:
model2.transform(['something value of something'], embeddings=embeddings.reshape(-1,1).T)

(array([178]),
 array([[0.85173   , 0.8124365 , 0.8275846 , 0.79675114, 0.8312795 ,
         0.79099107, 0.82853436, 0.7720464 , 0.8183088 , 0.8231032 ,
         0.8050834 , 0.8214216 , 0.79972136, 0.8172016 , 0.80349857,
         0.8278321 , 0.7770744 , 0.81880385, 0.79141295, 0.81423116,
         0.8110881 , 0.838158  , 0.8344958 , 0.78503776, 0.76430553,
         0.7985776 , 0.82615566, 0.82270586, 0.80396366, 0.8028486 ,
         0.8304247 , 0.8085565 , 0.8091005 , 0.8086864 , 0.82351017,
         0.7960256 , 0.804183  , 0.81962353, 0.804905  , 0.8058171 ,
         0.7829537 , 0.83115655, 0.79223996, 0.80756915, 0.78401685,
         0.81519985, 0.802927  , 0.7957207 , 0.77032256, 0.7943817 ,
         0.847141  , 0.800664  , 0.80675423, 0.8199898 , 0.7987021 ,
         0.79697645, 0.7571772 , 0.8018681 , 0.82451797, 0.8010155 ,
         0.81687135, 0.79841435, 0.8044724 , 0.7971337 , 0.80732256,
         0.8287896 , 0.81218433, 0.8192041 , 0.7856287 , 0.7865114 ,
         0.78529036

In [15]:
ect.bertopic_model.find_topics('sample_value')

([178, 49, 359, -1, 260],
 [0.8246786362181735,
  0.8244184209327878,
  0.8212337927460798,
  0.8185488135200789,
  0.8167866036205779])

In [18]:
model2.find_topics('sample_value')

([178, 49, 359, -1, 260],
 [0.82467854, 0.82441854, 0.82123375, 0.81854886, 0.81678665])

In [10]:
model2.probabilities_

In [5]:
ect.

Type:        EmbeddingsClusterTopics
String form: <__main__.EmbeddingsClusterTopics object at 0x167061a10>
Docstring:   <no docstring>